### ISSUE TITLE
XML-RPC functions returning 'null' generate malformed responses

### ISSUE THREAD

**Issue by grawity** [moodlehq/moodle-webservice_xmlrpc#6]
It seems that functions returning `null` fail to generate an XML-RPC response at all. For example, the function "core_user_delete_users" returns null, so when it's called via XML-RPC, nothing is returned in the HTTP response body (Content-Length: 0). The Python xmlrpc.client's XML parser understandably treats this as an error.

```
Traceback (most recent call last):
  File "/home/grawity/***/Moodle/rpc.py", line 96, in delete_users
    result = self.api.core_user_delete_users(ids)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  <...>
  File "/usr/lib/python3.11/xmlrpc/client.py", line 460, in close
    parser.Parse(b"", True) # end of data
    ^^^^^^^^^^^^^^^^^^^^^^^
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

I found that in webservice/xmlrpc/locallib.php, the function `prepare_response()` isn't actually handling the case when `returns_desc` is found to be "empty" – `$this->response` isn't being set at all.

(Previous [MDL-72522](https://tracker.moodle.org/browse/MDL-72522) was closed as "fixed" but presumably only due to the plugin being removed from core; it doesn't seem to be actually fixed.)

**Comment by stronk7** [comment]
Hi @grawity ,

and what should be returned by xmlrpc (sorry I'm not an specialist there) when empty or null information is returned by the underlying moodle functions? I'm happy to modify the plugin to whatever is more correct for those cases.

Ciao :-)

**Comment by grawity** [comment]
It should still return an XML body that's a well-formed XML-RPC response – I'd probably expect `<nil/>` as the value, something like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <params>
    <param>
      <value>
        <nil/>
      </value>
    </param>
  </params>
</methodResponse>
```

Though, apparently nil is kind of an extension and not part of original XML-RPC spec, and PHP's xmlrpc_encode_request() instead produces this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <params>
    <param/>
  </params>
</methodResponse>
```

which is still acceptable – Python's xmlrpc.client does not complain, converting it into an empty tuple `()` which isn't quite the same but does the job well enough.

It would also make sense to return a (fake) TRUE (`<boolean>1</boolean>`) for most methods that return null on success.

Any of those are better than a completely empty (0-byte) response that makes the XML-RPC client die.

**Comment by stronk7** [comment]
Hi @grawity ,

thanks for your explanations, they help.

I've applied the same changes that you did above to the current `prepare_response()` method (that now is slightly different from the one you're using).

Here there are the differences. I've left out the "empty else" because that's another problem (non-empty desc and not-null returns) that surely needs to be considered apart from this (null returns) case.

https://github.com/moodlehq/moodle-webservice_xmlrpc/commit/e051fe4c3208c37c203e34c6aedafac93cc0bae8

Only problem that I see is that, with the code in place, the tests are returning exactly this:

```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <params/>
</methodResponse>
``` 

Is that ok enough for your client?

**Comment by stronk7** [comment]
Thanks @grawity ,

I've just tagged and released 1.0.4 that includes the changes commented above.
- Github: https://github.com/moodlehq/moodle-webservice_xmlrpc/releases/tag/1.0.4
- Moodle plugins directory: https://moodle.org/plugins/webservice_xmlrpc/1.0.4/29991

Thanks for all your help!

Ciao :-)

**Comment by grawity** [comment]
Thanks very much; now I can finally get rid of the code that marked users as "deleted" via SQL... For reference, the Python XML-RPC client code to test with:

```python
import xmlrpc.client
import pprint

site = "https://moodle.example.com"
token = "asdf"
mdl = xmlrpc.client.ServerProxy(f"{site}/webservice/xmlrpc/server.php?wstoken={token}",
                                # Dump raw request/response body to stderr
                                verbose=True)

users = [{"username": "foo12345",
          "auth": "saml2",
          "firstname": "Fred",
          "lastname": "Foobar",
          "email": "test@example.com"}]
res = mdl.core_user_create_users(users)
print(f"Created => {res!r}")

userids = [x["id"] for x in res]
res = mdl.core_user_delete_users(userids)
print(f"Deleted => {res!r}")
```
